
# -------------------------------------------------------------------
# Blueprint Metadata
# Version:      1.0.2
# Last Updated: 2025-09-18
# Author:       Michael Dorchain
# Source:       https://github.com/mdorchain/home-assistant-blueprints/
#
# Changelog:
#   1.0.1 (2025-09-13) - Initial release
#   1.0.2 (2025-09-18) - Updated condition template 
#
# Notes:
# - Automatically turn a device back on after it turns off by itself (not by a user, automation, or script).  
# - Useful for Xiaomi fans, air conditioners, or lights that power off unexpectedly.
# -------------------------------------------------------------------

blueprint:
  name: Auto Recover Device
  description: >
    Automatically turn a device back on after it turns off by itself
    (not by a user, automation, or script).  
    Useful for Xiaomi fans, air conditioners, or lights that power off unexpectedly.
  domain: automation
  input:
    target_entity:
      name: Target entity
      description: The device to monitor (fan, climate, light, switch, etc.)
      selector:
        entity: {}
    delay_time:
      name: Delay before recovery
      description: Time to wait before turning the device back on
      default: "00:15:00"
      selector:
        duration:

mode: restart

trigger:
  - platform: state
    entity_id: !input target_entity
    to: "off"

condition:
  - condition: template
    value_template: >
      {{ trigger.to_state.context.user_id is none and trigger.to_state.context.parent_id is none }}

action:
  - delay: !input delay_time
  - service: homeassistant.turn_on
    target:
      entity_id: !input target_entity
