# -------------------------------------------------------------------
# Blueprint
# Version:        1.0.2
# Last Updated:   2026-10-05
# Author:         Michael Dorchain
# Source:         https://github.com/mdorchain/home-assistant-blueprints/
#
# Changelog:
#   1.0.0 - initital release
#   1.0.1 - Compatibility fixes for Home Assistant 2026.10.0
#   1.0.2 - Switch back to command mode
# -------------------------------------------------------------------

blueprint:
  name: ZHA - Tuya TS004F 4-Button Switch
  description: Automate your Tuya 4-Button Switch using ZHA events.
  domain: automation
  homeassistant:
    min_version: 2023.9.0
  input:
    tuya_4button_switch:
      name: Tuya TS004F 4-Button Switch
      description: Tuya TS004F 4-Button Switch to use
      selector:
        device:
          filter:
            - manufacturer: Tuya
            - manufacturer: _TZ3000_xabckq1v
          multiple: false
    button_1_click:
      name: Button 1 click
      description: Action to run on button upper-left single press
      default: []
      selector:
        action: {}
    button_2_click:
      name: Button 2 click
      description: Action to run on button upper-right single press
      default: []
      selector:
        action: {}
    button_2_long_press:
      name: Button 2 - Long Press Dim-Up
      description: Action to run on button upper-right long press
      default: []
      selector:
        action: {}
    button_3_click:
      name: Button 3 - Click
      description: Action to run on button lower-left single press
      default: []
      selector:
        action: {}
    button_4_click:
      name: Button 4 - Click
      description: Action to run on button lower-right single press
      default: []
      selector:
        action: {}
    button_4_long_press:
      name: Button 4 - Long Press Dim-Down
      description: Action to run on button lower-right long press
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'tuya_4button_switch'
action:
- variables:
    command: '{{ trigger.event.data.command }}'
    attribute_name: '{{ trigger.event.data.args.attribute_name }}'
    attribute_value: '{{ trigger.event.data.args.value }}'
    step_mode: '{{ trigger.event.data.params.step_mode }}'
    move_mode: '{{ trigger.event.data.params.move_mode }}'
- choose:
  - conditions: '{{ true }}'
    sequence:
        - service: notify.persistent_notification
          data:
            message: 'attribute_name: {{ attribute_name }}, step_mode: {{ step_mode }}, move_mode: {{ move_mode }}, attribute_value: {{ attribute_value }}'
            title: '{{ command }}'
  - conditions: '{{ command == ''step'' }}'
    sequence:
    - choose:
      - conditions: '{{ step_mode == ''StepMode.Up'' }}'
        sequence: !input 'button_2_click'
      - conditions: '{{ step_mode == ''StepMode.Down'' }}'
        sequence: !input 'button_4_click'
  - conditions: '{{ command == ''move'' }}'
    sequence:
    - choose:
      - conditions: '{{ move_mode == 0 }}'
        sequence: !input 'button_2_long_press'
      - conditions: '{{ move_mode == 1 }}'
        sequence: !input 'button_4_long_press'
  - conditions: '{{ command == ''attribute_updated'' }}'
    sequence:
    - choose:
      - conditions: '{{ attribute_name == ''on_off'' and attribute_value == 0 }}'
        sequence: !input 'button_3_click'
      - conditions: '{{ attribute_name == ''on_off'' and attribute_value == 1 }}'
        sequence: !input 'button_1_click'